# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    container_name: mysql_server
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: mysql_server_adminer

  app:
    depends_on:
      - db
    image: phindock/docker101tutorial:dockerizedspringbootapp
    restart: always
    ports:
      - 8081:8080
    container_name: dockerizdspringbootapp